Add Delete Button to Personal Sections Table
ucsb-cs156-s24/proj-courses-s24-4pm-4 pull request #29
Opened 2024-05-23 00:43 UTC by WinbertZhang

This PR adds a delete button to the personal sections table allowing users to remove all associated lectures and sections for a course. 

Navigate to /personalschedules/details/1:
<img width="1419" alt="Screenshot 2024-05-22 at 5 42 26 PM" src="https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/assets/17103790/3e4ec630-84ee-46f2-a586-12821d6e1bee">

Press on the delete button for any course, and the result is as follows:
<img width="1419" alt="Screenshot 2024-05-22 at 5 43 08 PM" src="https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/assets/17103790/a0e3611c-bb14-46e4-aa57-46402ddcdead">

Closes #2

2024-05-24 00:07 UTC, tihdiR approved these changes
LGTM

2024-05-24 01:06 UTC, AnikaArora requested changes
Please include the dokku link

2024-05-26 02:13 UTC, WinbertZhang commented
> Please include the dokku link

Updated PR Description with dokku link: https://team04-winbertzhang-dev02.dokku-04.cs.ucsb.edu/

2024-05-27 00:20 UTC, WinbertZhang commented
This PR is to be merged after #28 is merged.

2024-05-28 20:08 UTC, pconrad commented on frontend/src/main/utils/sectionUtils.js
> +    url: "/api/personalSections/delete",
```suggestion
    url: "/api/courses/user",
```

Why not use the existing endpoint?

2024-05-28 20:09 UTC, pconrad commented on frontend/src/main/utils/sectionUtils.js
> +      enrollCd: enrollCode,
```suggestion
     id: id,
```

2024-05-28 20:09 UTC, pconrad commented on frontend/src/main/utils/sectionUtils.js
> +  const enrollCode = cell.row.values["classSections[0].enrollCode"];
```suggestion

```

2024-05-28 20:48 UTC, pconrad approved these changes
LGTM

2024-05-28 20:49 UTC, merged