BUG: Modal for Adding Courses on Basic Course Search Page Displays All Schedules
ucsb-cs156-s24/proj-courses-s24-4pm-4 pull request #33
Opened 2024-05-24 08:18 UTC by andersonlee3

- fixed the bug so that the modal only displays schedules for the corresponding quarter
- when no schedules match, displays a message saying no schedules exist for the quarter the user is searching on and link to create a new schedule

dokku: [https://al-proj-courses.dokku-04.cs.ucsb.edu](url)
Closes #1

2024-05-25 03:10 UTC, andrew344c submitted a review, later dismissed
LGTM

2024-05-26 21:36 UTC, pconrad requested changes
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-26 21:36 UTC, pconrad commented on frontend/src/main/components/PersonalSchedules/PersonalScheduleSelector.js
> +  //const localSearchSchedule = localStorage.getItem(controlId);
Commented out code: 
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-26 21:36 UTC, pconrad commented on frontend/src/main/components/PersonalSchedules/PersonalScheduleSelector.js
> +    //localSearchSchedule || schedule,
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-26 21:36 UTC, pconrad commented on frontend/src/main/components/PersonalSchedules/PersonalScheduleSelector.js
> +//import { useBackend } from "main/utils/useBackend";
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-26 23:50 UTC, andersonlee3 commented on frontend/src/main/components/PersonalSchedules/PersonalScheduleSelector.js
> +    //localSearchSchedule || schedule,
done.

2024-05-26 23:50 UTC, andersonlee3 commented on frontend/src/main/components/PersonalSchedules/PersonalScheduleSelector.js
> +//import { useBackend } from "main/utils/useBackend";
done.

2024-05-27 02:43 UTC, andrew344c approved these changes
LGTM

I don't think I see any commented out code

2024-05-28 20:50 UTC, merged