Added Improvement Course History Search Feature
ucsb-cs156-s24/proj-courses-s24-4pm-4 pull request #38
Opened 2024-05-27 04:20 UTC by JLowe32

In this PR, added feature that allowed for a search that had a prefix to give the same classes that didn't have a prefix. An example would be CS130A that gave the same output as a search of 130A or 130.

Closes #11

2024-05-28 00:16 UTC, tihdiR approved these changes
LGTM

2024-05-28 20:35 UTC, whuang602 requested changes
A deployment link or demonstration would be great.

2024-05-28 21:38 UTC, andrew344c commented
Deployment of PR branch: https://ac-courses.dokku-04.cs.ucsb.edu/
Specific page of changed component: https://ac-courses.dokku-04.cs.ucsb.edu/courseovertime/search

2024-05-29 00:12 UTC, andersonlee3 approved these changes
LGTM

2024-05-29 22:23 UTC, pconrad approved these changes
LGTM

2024-05-29 22:24 UTC, merged